
[functions.notifiy-telegram]
enabled = true
verify_jwt = true
import_map = "./functions/notifiy-telegram/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notifiy-telegram/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notifiy-telegram/*.html" ]

[functions.notifiy-telegram-user]
enabled = true
verify_jwt = true
import_map = "./functions/notifiy-telegram-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notifiy-telegram-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notifiy-telegram-user/*.html" ]
